# -*- coding: utf-8 -*-
"""eda_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVq4CL5nq6aGODAyldmMNZN16FeEhLLN
"""

import pandas as pd
import numpy as np

# Load raw dataset
file_path = "3.retail_store_sales Assignment 1.csv"
raw_df = pd.read_csv(file_path)

print("=" * 60)
print("1. DATA DATASET SHAPE & TYPES AUDIT")
print("=" * 60)
print(f"Total Rows: {raw_df.shape[0]:,}")
print(f"Total Columns: {raw_df.shape[1]}")
print("\nData types per column:")
print(raw_df.dtypes)

print("\n" + "=" * 60)
print("2. MISSING VALUES AUDIT")
print("=" * 60)
missing_audit = pd.DataFrame({
    'Missing Count': raw_df.isnull().sum(),
    'Missing Percentage (%)': (raw_df.isnull().sum() / len(raw_df) * 100).round(2)
})
print(missing_audit[missing_audit['Missing Count'] > 0])

print("\n" + "=" * 60)
print("3. DUPLICATE ROWS AUDIT")
print("=" * 60)
print(f"Exact Duplicate Rows Count: {raw_df.duplicated().sum()}")
print(f"Duplicate Transaction ID Count: {raw_df['Transaction ID'].duplicated().sum()}")

print("\n" + "=" * 60)
print("4. HEAD PREVIEW (FIRST 5 ROWS)")
print("=" * 60)
display(raw_df.head())

# ==========================================
# STEP 2: DATA CLEANING & FEATURE ENGINEERING
# ==========================================

def clean_retail_data(df_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans raw retail transaction dataset by handling missing values,
    correcting data types, and engineering time features.
    """
    df_clean = df_raw.copy()

    # 1. Standardize and parse Transaction Date (DD/MM/YYYY)
    df_clean['Transaction Date'] = pd.to_datetime(
        df_clean['Transaction Date'], dayfirst=True, errors='coerce'
    )

    # Feature Engineering: Extract Year and Year-Month
    df_clean['Year'] = df_clean['Transaction Date'].dt.year
    df_clean['YearMonth'] = df_clean['Transaction Date'].dt.to_period('M')

    # 2. Impute missing Price Per Unit using formula: Total Spent / Quantity
    price_missing_mask = (
        df_clean['Price Per Unit'].isnull() &
        df_clean['Total Spent'].notnull() &
        df_clean['Quantity'].notnull()
    )
    df_clean.loc[price_missing_mask, 'Price Per Unit'] = (
        df_clean.loc[price_missing_mask, 'Total Spent'] / df_clean.loc[price_missing_mask, 'Quantity']
    )

    # 3. Handle missing boolean values for Discount Applied
    df_clean['Discount Applied'] = (
        df_clean['Discount Applied'].infer_objects(copy=False).fillna(False).astype(bool)
    )

    # 4. Fill missing Item names
    df_clean['Item'] = df_clean['Item'].fillna("Unspecified Item")

    # 5. Drop remaining rows where primary target Total Spent is unrecoverable
    df_clean = df_clean.dropna(subset=['Total Spent']).copy()

    return df_clean

# Run cleaning function
cleaned_df = clean_retail_data(raw_df)

print("Data Cleaning Completed!")
print(f"Cleaned Dataset Shape: {cleaned_df.shape}")
print("\nRemaining Missing Values Check:")
print(cleaned_df.isnull().sum())

# ==========================================
# STEP 3: DESCRIPTIVE STATISTICS & EDA
# ==========================================

def perform_descriptive_stats(df: pd.DataFrame):
    """
    Computes summary statistics for numerical variables, aggregated revenue
    across categorical features, and the feature correlation matrix.
    """
    print("=" * 65)
    print("1. NUMERICAL DESCRIPTIVE STATISTICS")
    print("=" * 65)
    num_cols = ['Price Per Unit', 'Quantity', 'Total Spent']
    num_stats = df[num_cols].describe().round(2)
    display(num_stats)

    print("\n" + "=" * 65)
    print("2. CATEGORICAL REVENUE BREAKDOWN")
    print("=" * 65)
    cat_summary = (
        df.groupby('Category')['Total Spent']
        .agg(Transaction_Count='count', Total_Revenue='sum', Average_Spent='mean')
        .reset_index()
        .sort_values(by='Total_Revenue', ascending=False)
    )
    display(cat_summary)

    print("\n" + "=" * 65)
    print("3. FEATURE CORRELATION MATRIX")
    print("=" * 65)
    corr_matrix = df[num_cols].corr().round(3)
    display(corr_matrix)

# Run descriptive statistics analysis
perform_descriptive_stats(cleaned_df)

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Set global aesthetic style for charts
sns.set_theme(style="whitegrid", palette="muted")


# ==========================================
# STEP 4: DEDICATED VISUALISATION FUNCTIONS
# ==========================================


def generate_relational_plot(
    df: pd.DataFrame, output_name: str = "relational_plot.png"
):
    """Plot Type 1: Relational Plot

    Scatter plot analyzing the relationship between Quantity Purchased and
    Total Spent across Product Categories.
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    sns.scatterplot(
        data=df,
        x="Quantity",
        y="Total Spent",
        hue="Category",
        alpha=0.7,
        s=60,
        ax=ax,
    )

    ax.set_title(
        "Relational Analysis: Quantity Purchased vs. Total Spent by Category",
        fontsize=13,
        fontweight="bold",
        pad=15,
    )
    ax.set_xlabel("Quantity Purchased (Units)", fontsize=11)
    ax.set_ylabel("Total Spent ($)", fontsize=11)
    ax.legend(title="Product Category", bbox_to_anchor=(1.05, 1), loc="upper left")

    plt.tight_layout()
    plt.savefig(output_name, dpi=300)
    plt.show()


def generate_categorical_plot(
    df: pd.DataFrame, output_name: str = "categorical_plot.png"
):
    """Plot Type 2: Categorical Plot

    Grouped bar chart comparing Total Revenue across Product Categories and
    Sales Channel Locations.
    """
    fig, ax = plt.subplots(figsize=(12, 6))

    cat_sales = (
        df.groupby(["Category", "Location"])["Total Spent"]
        .sum()
        .reset_index()
    )

    sns.barplot(
        data=cat_sales,
        x="Category",
        y="Total Spent",
        hue="Location",
        palette="Set2",
        ax=ax,
    )

    ax.set_title(
        "Categorical Analysis: Total Revenue by Category and Sales Channel",
        fontsize=13,
        fontweight="bold",
        pad=15,
    )
    ax.set_xlabel("Product Category", fontsize=11)
    ax.set_ylabel("Total Revenue ($)", fontsize=11)
    plt.xticks(rotation=30, ha="right")
    ax.yaxis.set_major_formatter("${x:,.0f}")

    plt.tight_layout()
    plt.savefig(output_name, dpi=300)
    plt.show()


def generate_statistical_plot(
    df: pd.DataFrame, output_name: str = "statistical_plot.png"
):
    """Plot Type 3: Statistical Plot

    Boxplot illustrating the empirical distribution of spending across Payment
    Methods.
    """
    fig, ax = plt.subplots(figsize=(10, 6))

    sns.boxplot(
        data=df,
        x="Payment Method",
        y="Total Spent",
        hue="Payment Method",
        palette="Pastel1",
        legend=False,
        showmeans=True,
        meanprops={
            "marker": "o",
            "markerfacecolor": "red",
            "markeredgecolor": "red",
        },
        ax=ax,
    )

    ax.set_title(
        "Statistical Analysis: Transaction Total Spent Distribution by Payment Method",
        fontsize=13,
        fontweight="bold",
        pad=15,
    )
    ax.set_xlabel("Payment Method", fontsize=11)
    ax.set_ylabel("Total Spent ($)", fontsize=11)

    plt.tight_layout()
    plt.savefig(output_name, dpi=300)
    plt.show()


# Execute chart generation functions
generate_relational_plot(cleaned_df)
generate_categorical_plot(cleaned_df)
generate_statistical_plot(cleaned_df)